### ISSUE TITLE
No convergence issue with a complicated structure

### ISSUE THREAD

**Issue by epidko** [EPiCs-group/epic-mace#40]
When attempted to build an octahedral  complex of Co(2+) with NC1=CC(C[N:1](CC2=CC(N)=[N:1]C=C2)CC2=CC(NC([O-:1])=O)=[N:1]C=C2)=CC=[N:1]1 |c:10,12,22,24,26,28,t:1,7,16| and an H- ligand. No convergence was achieved and code kept running.

**Comment by IvanChernyshov** [comment]
Recreated in the GUI repo: [link](https://github.com/IvanChernyshov/mace-notebooks)
